version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - name: Build Container Installer
  uses: JasonN3/build-container-installer@v1.2.3

