# image will be published to ghcr.io/<user>/<name>
name: zoeys-first-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: gnome-extensions
    install:
      - 6433
      - 615
      - 6670
                
  - type: rpm-ostree
    install:
      - hyfetch
      - vim
      - hugo
      - gnome-boxes
      - fish
    remove:
      - firefox
      - firefox-langpacks 
      - gnome-tweaks
      - nvtop

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      repo-name: flathub-user
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-title: "Flathub" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - io.github.alainm23.planify
        - io.github.finefindus.Hieroglyphic
        - com.github.johnfactotum.Foliate
        - org.sigxcpu.Livi
        - com.notesnook.Notesnook
        - dev.vencord.Vesktop
        - org.kde.krita
        - org.mozilla.Thunderbird
        - com.ulduzsoft.Birdtray
        - io.gitlab.theevilskeleton.Upscaler
        - com.github.neithern.g4music
        - io.github.shiftey.Desktop
        - com.github.flxzt.rnote
        - com.github.johnfactotum.Foliate
        - com.toolstack.Folio
        #GNOME Desktop 
        - org.gnome.Loupe
        - net.nokyan.Resources
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Papers
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.font-viewer
        - org.gnome.clocks
        - org.sigxcpu.Livi
        - org.gnome.Logs

      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

