# image will be published to ghcr.io/<user>/<name>
name: zoeys-first-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /                
      - usr: /usr
      - etc: /etc
  - type: gnome-extensions
    install:
      - 6433 # App Menu Is Back
      - 615  # AppIndicator Support
      - 6670 # Bluetooth Battery Meter
      - 4691 # PIP On Top
      - 517  # Caffeine
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/fz0x1/zola/repo/fedora-%OS_VERSION%/fz0x1-zola-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/medzik/jetbrains/repo/fedora-%OS_VERSION%/medzik-jetbrains-%OS_VERSION%.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      - hyfetch
      - vim
      - hugo
      - gnome-boxes
      - fish
      - code
      - steam-devices
      - goverlay
      - zola
      - rhythmbox
      - rhythmbox-alternative-toolbar
      - yt-dlp
      - pycharm-community
      - intellij-idea-community
      - android-studio
      - webstorm
      - rustrover
    remove:
      - firefox
      - firefox-langpacks 
      - gnome-tweaks
      - nvtop
      - yelp
      - gnome-tour
      - gnome-system-monitor 
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      repo-name: flathub-user
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-title: "Flathub" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        #Essentials
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - com.ulduzsoft.Birdtray
        - io.gitlab.theevilskeleton.Upscaler
        - io.github.alainm23.planify
        - dev.vencord.Vesktop
        #Office
        - com.notesnook.Notesnook
        - org.libreoffice.LibreOffice
        - com.github.flxzt.rnote
        - com.github.johnfactotum.Foliate
        - com.toolstack.Folio
        - io.github.finefindus.Hieroglyphic
        - org.zotero.Zotero
        - com.slack.Slack
        #Programming
        - io.github.shiftey.Desktop #Github Desktop Linux
        - dev.zed.Zed
        #Gaming
        - com.valvesoftware.Steam
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.heroicgameslauncher.hgl
        - org.prismlauncher.PrismLauncher
        - com.github.mtkennerly.ludusavi
        #Music/Content-Creation
        - com.github.neithern.g4music
        - org.kde.krita
        - org.musescore.MuseScore
        - fm.reaper.Reaper
        - org.audacityteam.Audacity
        - org.kde.kdenlive
        - org.ardour.Ardour
        - org.zrythm.Zrythm
        - fr.handbrake.ghb
        #GNOME Desktop 
        - org.gnome.DejaDup
        - org.gnome.Loupe
        - net.nokyan.Resources
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Papers
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.font-viewer
        - org.gnome.clocks
        - org.sigxcpu.Livi
        - org.gnome.Logs
        - org.gnome.NautilusPreviewer
        - com.obsproject.Studio.Plugin.GStreamerVaapi
        - com.obsproject.Studio.Plugin.Gstreamer
        - org.gnome.Builder

      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: gschema-overrides
    include:
        - zz1-zilverblue.gschema.override

        