# image will be published to ghcr.io/<user>/<name>
name: zoeys-first-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: gnome-extensions
    - 6433
    - 615
    - 6670
      - 6670
                
  - type: rpm-ostree
    repos:
      https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      https://packages.microsoft.com/keys/microsoft.asc
    install:
      - code
      - hyfetch
      - vim
      - hugo
      - steam
    remove:
      - firefox
      - firefox-langpacks 

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      repo-name: flathub
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-title: "Flathub" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - io.github.alainm23.planify
        - io.github.finefindus.Hieroglyphic
        - com.github.johnfactotum.Foliate
        - org.sigxcpu.Livi
        - com.notesnook.Notesnook
        - dev.vencord.Vesktop
        - org.kde.krita
        - org.mozilla.Thunderbird
        - com.ulduzsoft.Birdtray
        - io.gitlab.theevilskeleton.Upscaler
        - com.github.neithern.g4music
        - io.github.shiftey.Desktop
        - com.github.flxzt.rnote
        - com.github.johnfactotum.Foliate
        - com.toolstack.Folio
        - net.nokyan.Resources
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

